name: Code Quality Check and Build

on:
  push:
    branches:
      - main

jobs:
  code_quality_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Run Super-Linter
        uses: github/super-linter@v5 
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  print_variables:
    runs-on: ubuntu-latest
    env:
      USERNAME: "OLUWAKEMI-AKINSIKU" 
    steps:
      - name: Print GitHub Token and Username
        run: |
          echo "GitHub Token: ${{ secrets.GIT_TOKEN }}"
          echo "GitHub Username: ${{ env.USERNAME }}"
      - name: Debug Environment Variables
        run: env


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build or List Files
        run: ls -R
