name: Code Quality Check and Build

on:
  push:
    branches:
      - main

jobs:
  code_quality_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_BASH: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Print GitHub Token and Username
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "GitHub Token: $GITHUB_TOKEN"
          echo "GitHub Username: $USERNAME"


  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build or List Files
        run: ls -la

      - name: make script executable
        run: chmod +x num_count.sh

      - name: run a bash script
        run: ./num_count.sh
